import React from 'react';
import Box from '@mui/material/Box';
import { H2, H3, Subtitle, P, OL, Quot } from 'src/components/commonStyled';
import p396image from 'src/assets/p396.jpg';
import sanGif from 'src/assets/san.gif';

const Morality = () => {
  return (
    <Box sx={{ background: 'white', borderRadius: 2, padding: 4, boxShadow: 1 }}>
      <H2>{`Morality or beyond: The Neo-Confucian confrontation with Mahaayaana Buddhism`}</H2>
      <Subtitle>{`By Charles Wei-hsun Fu(a)`}</Subtitle>
      <Subtitle>{`Philosophy east and west`}</Subtitle>
      <Subtitle>{`vol.23, no.3(1973), p 375-396`}</Subtitle>
      <Subtitle>{`(c) bye the University press of Hawaii`}</Subtitle>
      <div style={{ marginTop: '50px' }}>
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <img src={sanGif} style={{ objectFit: 'cover', width: '100%', maxWidth: '600px' }} />
        </div>
        <H3 style={{ textAlign: 'center' }}>{`P.375`}</H3>
        <H3 style={{ textAlign: 'center' }}>{`I`}</H3>
        <P>
          {`Confucianism can be characterized as a philosophical system of morality, humanistically designed to orient man's life toward the ultimate goal of "inner sagehood and outer kingliness" or "sublime transcendence right in everyday ethicosocial practice." To maintain the self-consistency and self-sufficiency of their moral tradition, the orthodox Confucianists since Mencius have tried hard to resist the force of all heterodox doctrines (yi-tuan(b) ) , notably Taoist philosophy and Mahaayaana Buddhism, both of which have exerted tremendous influences upon the reshaping of the Confucian tradition. In this article I shall critically examine the Neo-Confucian confrontation with Mahaayaana Buddhism in China. This is perhaps the most interesting and significant case of ideological "love and hate" in the whole history of Chinese philosophy and religion.`}
        </P>

        <P>
          {`It is a very striking fact that almost all the leading Neo-Confucianists confessed that they had been engaged, seriously or not, in Buddhist studies for many years before they made a prodigal's return to the Confucian path. Chou Tun-yi(c) (1017-1073), the forerunner of Neo-Confucian thought, was often said to be "a poor Zen fellow"; and his personal affiliation with Zen monks such as Ch'ang-tsung(d) or Fo-yin Liao-yuan(e) is undeniable.(1) Among the orthodox Neo-Confucianists he alone did not participate in any refutation of Buddhist thought. Chang Tsai(f) (1020-1077) , who first led the Neo-Confucian attack against Buddhism, studied Buddhist and Taoist works extensively when young, then finally realized that "My Way is self-sufficient, why should I seek other things?"(2) Ch'eng Yi(g) (1033-1107) said of his brother that"he [Ch'eng Hao(h) (1032-1085)] drifted among the various schools of thought and went in and out of the Taoist and Buddhist schools for almost ten years. Finally he returned to the Six Classics and only then did he find the Way."(3) The greatest Neo-Confucian synthesizer, Chu Hsi(i) (1130-1200), admitted in his letter to Chiang Yuan-shih(j) that he had been attracted by Buddhism and Taoism for more than ten years and "begin to find the main direction I should take after my acquaintance in recent years with those who know the Way."(4) And both Lu Hsiang-shan(k) (1139-1193) and Wang Yang-ming(l) (1472-1529), the two greatest leaders of the Mind school, were often accused by other Neo-Confucianists that their teachings were too Zennist. Wang, in`}
        </P>

        <OL>
          <li>{`Charles Wei-hsun Fu is Assistant Professor, Department of Religion, Temple University, Philadelphia. Daijo Tokiwa, Shina ni okeru bukkyo to jukyo dokyo(bg) [Buddhism in relation to Confucianism and Taoism in China] (Tokyo: Toyo Bunko, 1930), p. 205.`}</li>
          <li>{`Chang Tzu ch'uan-shu(bh) [Complete works of Master Chang] (Taipei: Chunghua Book Co., 1968), 15:11A.`}</li>
          <li>{`Wing-tsit Chan, A Source Book in Chinese Philosophy (Princeton: Princeton University Press, 1963), p. 519 (hereafter cited as Source Book).`}</li>
          <li>{`Chu Tzu ta-ch'uan(bi) [Complete literary works of Master Chu] (Taipei: Chunghua Book Co., 1966], 38:34A.`}</li>
        </OL>

        <P>{`particular, was said to love reciting the Platform Suutra of the Sixth Patriarch. And according to Ch'en Chien(m), "Yang-ming's lectures throughout his life were based on his great esteem for both Bodhidharma and Hui-neng(n)."(5) Wang's followers even went so astray as to create "mad Zen" (k'udng-ch'an(o)). In general, when Neo-Confucian philosophers criticized each other, they often identified their opponents with the Buddhists, the typical example being Chu Hsi's vehement attack, in his later period, against Lu Hsiang-shan's doctrine as simply Zen. In any case, the Neo-Confucianists' study of or affinity with Mahaayaana Buddhism clearly reflects a hard inner struggle they passed through toward the original Confucian tradition, which had been overshadowed by Buddhism for nearly seven centuries.`}</P>

        <P>{`It is equally true that there had been a remarkable influence of Mahaayaana thought on Neo-Confucianism in almost every respect, such as metaphysical thinking, theory of human nature, method of mind-cultivation, linguistic expression in the colloquial style, or even the structure of private educational system (in terms of the master-disciple relations) . The ontological relation between wu-chi(p) (the Ultimateless) and t'ai-cli(q) (the Supreme Ultimate) in Chou Tun-yi's metaphysical system is often likened to that between wu-yen chen-ju(r) (the Inexpressible Suchness) and yi-yen chen-ju(s) (the Expressible Suchness) in the Awakening of Faith in the Mahaayaana. Daijo, Tokiwa(t) even argues that the very similarity here reflects Chou's attempt at the harmonization of the fundamental principles in both Confucianism and Buddhism.(6) Professor Ryoon Kubota(u) also notes that Chang Tsai's concept of t'ai-hsu(v) (the Great Vacuity), which is not mere nothingness but rather harbors the principle (of being) , seems to be influenced by the notion of being in the Vij~naanavaada and the Hua-yen(w) philosophy. And Chang's division of heavenly nature and material nature is said to be made by way of the hint he got from the 'Suura.mgama-samaadhi Suutra.(7) In the case of the Ch'eng brothers, the sentences such as "The Tao (the metaphysical) is concrete things (the phenomenal) and concrete things are the Tao" or"Things are not outside the Tao and the Tao is not outside things" strongly suggest, in spite of their Confucian tone, the metaphysical influence of the doctrine of nonobstructive interpenetration of li(x) (reality) and shih(y) (phenomena) in Hua-yen Buddhism. Again, despite his unremitting attack upon Buddhism, Chu Hsi sometimes borrowed, among other things, the Hua-yen simile of "the moon reflected in ten thousand rivers" to illustrate his conception of the Supreme Ultimate or Heavenly Principle (t'ien-li(z) ) differentiated into ten thousand ethicoontological principles inherent`}</P>

        <OL start='5'>
          <li>{`Quoted in Bunyu Kusumoto, (bj) Oyomei no zenteki shiso kenkyu(bk) [A study in the Zennistic thought of Wang Yang-ming] (Nagoya: Nisshindo Shoten,1958), p. 29.`}</li>
          <li>{`Tokiwa, Shina ni okeru bukkyo, p. 218`}</li>
          <li>{`Ryoon Kubota, Shina judobutsu koshoshi(bl) [The interactions of Confucianism, Taoism, and Buddhism in China] (Tokyo: Daito shuppan-sha, 1943), pp. 219-220.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.377`}</H3>


        <P>{`in all things. Wang Yang-ming sometimes compared his notion of "innate knowledge of the good" to the Zen notion of the "original face."(8) And his definition of the substance of the mind in terms of "neither good nor evil," which puzzled or misled many of his disciples, was made undoubtedly under the profound influence of the Mahaayaana conception of the nondual mind. Furthermore, one can detect some strong influence of the Mahaayaana idea of the universal Buddha-nature in the Neo-Confucian identification of the principle (li) with either (human) nature or the mind.(9)`}</P>

        <P>{`Regarding the method and practice of mind-cultivation, the influence of Zen meditation on Lu-Wang idealists is unmistakable. Even Ch'eng Yi the rationalist, whenever he saw a man quietly sitting, was said to praise him very highly for showing a good spirit of learning (mind-cultivation).(10) But the most interesting case is probably that the difference between the Rationalist school of Ch'eng-Chu and the Idealist school of Lu-Wang is almost the same as the difference between the school of gradual enlightenment and that of sudden enlightenment in Zen, as was admitted even by the Neo-Confucian leaders of both camps. For example, when Chu Hsi likened the process of the investigation of things and extension of knowledge (for the sake of moral perfecting) to one's polishing the dusty mirror day by day until it becomes completely bright, he seemed to be imitating Shen-hsiu's(aa) "constant polishing of the mirror lest the dust should collect."(11) Whereas Wang Yang-ming's words "the mind of the sage is like a clear mirror.... it responds to all stimuli as they come and reflects everything"(l2) remind us of Hui-neng's doctrine of sudden awakening as expressed in his gaathaa about "the original purity of the mind." All these examples are sufficient to expose the complicated ideological relations between these two traditions that are apparently opposed to each other.`}</P>

        <P>{`Interestingly, the more orthodox Neo-Confucianists learned about Mahaayaana Buddhism, the more they found a great danger of it contaminating Confucian humanism. They all realized that it was quite difficult to distinguish Confucianism from Mahaayaana Buddhism on the surface; they, therefore, took much pains to clarify the differences between the two traditions in terms of deep structure. And they always taught their disciples that the Confucian tra-`}</P>

        <OL start='8'>
          <li>{`"Original state" in Wing-tsit Chan's translation. See Wang Yang-ming, Instrucions for Practical Living, trans. Wing-tsit Chan (New York: Columbia University Press, 1963), p.141 (hereafter cited as Instructions).`}</li>
          <li>{`Ch'eng-Chu rationalists identify nature with the Principle, while Lu-Wang idealists hold that "Mind is the Principle."`}</li>
          <li>{`Erh-Ch'eng ch'uan-shu(bm) [Complete works of the Ch'eng brothers] (Taipei: Chunghua Book Co., 1966), vol. 2, Wai-shu(bn) [Additional works], 12:9B.`}</li>
          <li>{`Philip B. Yampolsky, trans., The Platform Sutra of the Sixth Patriarch (New York: Columbia University Press, 1967), p. 130.`}</li>
          <li>{`Wang Yang-ming, Instructions, p. 27.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.378`}</H3>

        <P>
          {`dition was self-sufficient and self-consistent and that it was unnecessary to study Buddhism at all. As Chu Hsi said, "It is not necessary to examine the doctrines of Buddhism and Taoism deeply to understand them."(13) And Ch'eng Yi's advice to his students may represent the general negative attitude of the orthodox Neo-Confucianists toward Buddhism as a whole:`}
        </P>

        <Quot>{`If one tries to investigate all the Buddhist doctrines in order to accept or reject them, before he has done that, he will already have been converted to be a Buddhist....it is none better to determine, on the basis of facts, that the Buddhist doctrines are not in accord with those of the Sage. We already have in our Way whatever is correct in them. Whatever is incorrect will of course be rejected. It is simple and easy to stand firm this way.(14)`}</Quot>

        <P>
          {`Ironically enough, it was mainly through the challenge and stimulation of Mahaayaana Buddhist thought, especially the totalistic philosophy of the Hua-yen school and Zen, that the orthodox Neo-Confucianists began to realize the necessity of rediscovering the metaphysico-religious significance of the fundamental principles existent in early Confucian classics, and reestablished these principles as the chief philosophical weapon to launch forceful attacks against (Mahaayaana) Buddhism in China.`}
        </P>

        <H3 style={{ textAlign: 'center' }}>{`II`}</H3>
        <P>
          {`We may now ask: On what philosophical ground can the orthodox Confucianists justify the legitimacy of their refutation of all non-Confucian systems of thought as heterodoxy (yi-tuan)? (15) Although no Confucian philosophers have ever speculated systematically on this problem of justification, there are, I think, three fundamental principles of the Confucian tradition that are complementary to one another and which the orthodox Neo-Confucianists have reconstructed and used as the necessary, if not exhaustive, criteria for their judging or rejecting the truth claims made by any other philosophico-religious system. These fundamental principles are: (1) the principle of jen-yi(ab) (jen manifested in gradational love), (2) the principle of sublime transcendence (kao-ming(ac)), and (3) the principle of the Mean in everyday moral practice (chung-yung(ad)).`}
        </P>

        <P>
          {`The principle of jen (human-kindness) and yi(ae) (righteousness) is the alpha and omega of Confucian morality. Confucius did not give a conclusive definition of jen as an all-pervading virtue, but it is at least implied by his various answers that jen is what constitutes the necessary and sufficient moral`}
        </P>

        <OL start='13'>
          <li>{`Source Book, p. 646.`}</li>
          <li>{`Chu Hsi and Lu Tsu-ch'ien, eds., Reflections on Things at Hand, trans. Wing-tsit Chan (New York: Columbia University Press, 1967), p. 285.`}</li>
          <li>{`The word first appeared in the Analects of Confucius, though the implication of Confucius' words "It is indeed harmful to study heterodox doctrines" (2:16) is not all clear as far as the meaning of "hetered oxg" is concerned.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.379`}</H3>

        <P>{`nature of man; it is moral perfection as such. And it is Mencius' great contribution to develop a theory of human nature as originally good, by identifying jen with man's moral endowment. Further, he explores a new dimension of Confucian morality by building yi into the context of jen. By making explicit Confucius' idea that the essential difference between the (morally) superior man and the inferior man consists in the distinction between yi and profit, Mencius regards yi as the natural extension of jen appropriately practiced in different moral situations. It should be noted emphatically here that yi as situational "ought" also implies gradational love. The Five Constant Relations Mencius established, or the eight steps toward the realization of the ideal of jen or summum bonum specified in the Great Learning, are two significant examples to exhibit the nature of the principle of gradational love as against Yang Chu's(af) egoistic principle of "everyone for himself" or Mo Tzu's(ag) principle of mutual love without distinctions. The principle of jen-yi was thus used by Mencius as the fundamental criterion for his refutation of all non-Confucian doctrines at that time.(16)`}</P>

        <P>{`In their reconstruction of the principle of jen-yi, the orthodox Neo-Confucianists add two important points by way of Mahaayaana influence. The first point is that, beginning with Chang Tsai, all of them extend the moral notion of jen to cover the entire universe; jen (human-kindness --> universal-kindness) now becomes the ethico-ontological principle of universal love. The new ideal of life is, according to the Neo-Confucianists, to "form one body with the universe," especially emphasized by Ch'eng Hao, Lu Hsiang-shan, and Wang Yang-ming.(l7) The second point is that the Neo-Confucianists, Ch'eng Yi and Chu Hsi in particular, assume in their interpretation of Chang Tsai's "Western Inscription" the ethico-ontological truth of "Principle is one but manifestations are many" (li-yi fen-shu(ah)), by means of which they reaffirm the principle of jen-yi in terms of the harmonious unity of substance (universal love of all things) and function (gradational love beginning with filial piety).(18) The orthodox Neo-Confucianists are now able to use this principle`}</P>

        <OL start='16'>
          <li>{`From the moral point of view, Mencius was particularly against Yang Chu's egoism and Mo Tzu's mutual love without distinctions. See Source Book, p. 72.`}</li>
          <li>{`I have two points in mind in my rendering jen into English as "human-kindness" in early Confucianism and "universal-kindness" in Neo-Confucianism: (1) as a noun, "human-kindness" and "universal-kindness" can express well the ideas of "we are of the same, human kind" and "we (men, animals, and all other things in the entire universe) are of the same, universal kind" (or "we all form one body--the body of heaven-and-earth"); (2) as an adjective,"human-kind" and "universal-kind" can be used in the expressions such as "Confucius was human-kind to other men (in the moral sense) " and "Wang Yang-ming was universal-kind even to trees and flowers (in the ethico-ontological sense)."`}</li>
          <li>{`See Source Book, p. 499 and pp. 550-551. Ch'eng Yi says clearly: "To make no distinction in human relations and to be deluded in universal love to the extreme of recognizing no special relationship with the father, is to do violent injury to righteousness," p. 551.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.380`}</H3>

        <P>
          {`of jen-yi ontologized as the first philosophical weapon to open up their moral criticism of Buddhism in general.`}
        </P>

        <P>
          {`Since in the eyes of Neo-Confucian leaders, Buddhism (as well as Taoism) always has a strong tendency to transcend or escape from human morality, their first attack upon Buddhism is, of course, that the latter completely destroys the moral way of the sages. Lu Hsiang-shan, who strictly followed the Mencian line of moral reasoning, often said: "We see that the distinction between the Confucianists and the Buddhists as one for public-spiritedness and righteousness and the other for selfishness and profit is perfectly clear and that they are absolutely incompatible."(19) Lu's words here typically reflect the orthodox Neo-Confucianists' total depreciation of Buddhist transcendentalism. They unanimously accused the Buddhists of their lofty escape from human relations and ethicosocial obligations in the secular world. The Buddhists are too selfish because they "desert their parents and family, completely destory human relations, and live alone in the mountains and forests."(20) "If everyone becomes a Buddhist, then there will be no human relations, and nobody will take of this world."(21) The selfish escape of the Buddhists from this world is made out of their dread of the cycle of life-and-death (sa.msaara) as well as of their disdain for the ocean of suffering (du.hkha). They set up the false doctrines of karmic retribution, sa.msaaric world-systems, and numerous hells to deceive "people with low intelligence so they will be scared and do good."(22) Ch'eng Hao said that because the Buddhist mind is the mind of profit, the Buddhists are always talkative about how to rid themselves of the wheel of life-and-death, while the Confucian sages regard this as a matter of one's natural lot, originally assigned by Heaven (Nature), and therefore have nothing to fear and would not discuss it.(23) In short, the lofty escapism of the Buddhists is totally against the principle of jen-yi and should be rejected as heterodox. In his comparison of Taoism and Buddhism Chu Hsi said:"Chuang Tzu and Lao Tzu still did not completely destroy moral principles. In the case of [orthodox] Buddhism, human relations are already destroyed. When it comes to Zen, however, from the very start it wipes out all moral principles completely. Looked at this way, Zen has done the greatest harm."(24) In connection with their moral criticism of the Buddhist abandonment of the Confucian way of jen and yi, Neo-Confucian philosophers deeply expressed their metaphysical disagreement with the "negativistic" Weltanschauung of Buddhism in general. To meet the challenge of Mahaayaana metaphysics, they`}
        </P>

        <OL start='19'>
          <li>{`Source Book, p. 576`}</li>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 1, Yi-shu(bo) [Surviving works], 1:2B.`}</li>
          <li>{`Ibid., 2A:9A.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.381`}</H3>

        <P>{`enriched the unsystematized metaphysical thinking of early Confucianism manifested by the principle of sublime transcendence, then used it as the chief metaphysical criterion to refute the Mahaayaana (and Taoist) philosophy of nothingness which, they thought, tended to deny the reality of the world and human life. But here again they considered Mahaayaana Buddhism more harmful and dangerous than Taoism. Chu Hsi, for instance, said that in Taoism there is still Being after all; in Buddhism, however, everything is completely reduced to Nonbeing, for heaven and earth are considered as illusory and the Four Elements (earth, water, fire, and wind) as unreal.(25) Ch'eng Yi also said that Zen Buddhists' withdrawal from the world is just like a man's closing his eyes without seeing his own nose--yet the nose is still there!(26)`}</P>

        <P>{`The principle of sublime transcendence is peculiar to the Confucian tradition, which does not first set up a metaphysical or religious foundation and then derive an ethical conclusion from it. On the contrary, it establishes at the beginning the moral teaching of jen and yi, based on the Mencian intuitive belief in the original goodness of man as distinguishable from beasts, and then develops in the vertical (transcendental) direction what Mou Tsung-san(ai) calls "moral metaphysics"(27) as a natural offshoot of Confucian morality. A man of moral excellence (jen) who, like Mencius, finds "all things are already complete in myself" and accumulates a full amount of "magnificent moral energy" (hao-jan chih-ch'i(aj) ) throughout his tao-body, can transcend his "little self" and the mundane world to become a "citizen of Heaven," thereby reaching the highest sphere of man, the sphere of Heaven-and-Earth. A citizen of Heaven is not a man who escapes into what Chuang Tzu calls the"Not-Even-Anything Village" or the "field of Broad-and-Boundless,"(28) but is rather a man who"seeks to reach the greatest height and brilliancy and follows the path of the Mean."(29) In other words, this sublime transcendence is not to be divorced from the Confucian Mean of everyday moral practice (chung-yung) , which is the third fundamental principle.(30) Both the`}</P>

        <OL start='25'>
          <li>{`Chu Tzu yu-lei(bp) [Classified conversations of Chu Hsi] (Taipei: Cheng-chung Book Co., 1970, 2d ed.), 126:5B, vol. 8, p. 4826.`}</li>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 1, Yi-shu, 3:4B.`}</li>
          <li>{`See Mou Tsung-san, Hsin-t'i yu hsing-t'i(bq) [Mind and human nature] (Taipei: Cheng-chung Book Co., 1968), vol. 1, pp. 8-9.`}</li>
          <li>{`Burton Watson, trans., The Complete Works of Chuang Tzu (New York: Columbia University Press, 1968), p. 35.`}</li>
          <li>{`Source Book, p. 110.`}</li>
          <li>{`The principle of the Mean has two dimensions: (1) its external dimension refers to the Confucian "timely Mean" (shih-chung(br) ) appropriately practiced in all kinds of moral situations, as is shown in Confucius' words "To overstep is as same as to fall short" or in "the principle of measuring square" of the Great Learning; (2) its internal dimension appears in the first chapter of the Doctrine of the Mean, according to which what is essentially important in the process of perfecting one's moral nature is not simply that one is able to take a timely (morally fitting) action in everyday moral`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.382`}</H3>

        <P>{`principle of sublime transcendence and the principle of the Mean are thus inseparably united to form a very unique characteristic of the Confucian tradition in terms of metaphysical thinking, theory of human nature, as well as self-cultivation. Since it is based on this combined principle of "sublime transcendence right in the Mean of everyday moral practice" as well as on the principle of jen-yi, both early Confucianists and Neo-Confucianists think that they are able to refute all heterodox systems of thought as either lofty escapism or utilitarian pragmatism.(31) The former is too farsighted, while the latter too shortsighted.`}</P>

        <P>{`The principle of sublime transcendence, which is implicit in the Book of Mencius, the Doctrine of the Mean, as well as in the Classic of Changes, is reconstructed by the orthodox Neo-Confucianists by way of the influence of Mahaayaana metaphysics, especially the Hua-yen "round" (all-perfect) doctrine of the four Dharmadhaatus and the Tathaagatagarbha thought in, for example, the Awakening of Faith. Although the reconstructive work began with Chou Tun-yi's Explanation of the Diagram of the Supreme Ultimate, he had no particular intention of demonstrating the supremacy of the moral metaphysics of Confucianism as against Mahaayaana transcendentalism. Chang Tsai, however, was deeply involved in the metaphysical confrontation of Neo-Confucianism with Mahaayaana Buddhism. He contrasted his own philosophy of ch'i(ak) (ether) with the Buddhist philosophy of emptiness and concluded that "those Buddhists who believe in annihilation (nirvaa.na) expect departure without return"(32) and know nothing about the real nature of life and death, while the Confucianists regard the coming of death as simply one's return to the Great Vacuity--the original substance of ch'i--from which one came. "Whether integrated or disintegrated, it is my body just the same. One is qualified to discuss the nature of man when he realizes that death is not annihilation."(33) What is really wrong with Buddhist metaphysics is, Chang Tsai argues, that it "never studies exhaustively the principle (li), but considers everything to be the result of subjective illusion."(34) The Buddhists would never be able to understand Heavenly sequence or orderliness, which`}</P>

        <OL start='31'>
          <li>{`practice, but rather (in a deeper sense) that the state of one's moral mind always maintains equilibrium and harmony through constant sincere search within oneself. The Neo-Confucianists even extend the notion of the Mean to their theory of human nature. Ch'eng Hao, for example, says: "The human mind (in essence) is the same as that of plants and trees, birds and animals. It is only that man receives at birth the Mean of Heaven and Earth (balanced material force)," Source Book, p. 527. 31 Two examples of lofty escapism, from the Confucian point of view, are Buddhism and Taoism; while utilitarian pragmatism is found in the Legalist school of ancient China or some nonorthodox Neo-Confucianists like Ch'en Liang and Yeh Shih in the Sung dynasty.`}</li>
          <li>{`Chang Tzu ch'uan-shu, 2:2A.`}</li>
          <li>{`Source Book, p. 501.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.383`}</H3>

        <P>{`is the principle of change, manifested in "the successive movements of yin and yang which cover the entire universe, penetrate day and night, and form the standard of the great Mean in the three ultimates of heaven, earth, and man."(35) As a monist of ch'i, however, Chang Tsai touched on the notion of Principle only sketchily. It was through the Ch'eng brothers and Chu hsi that the metaphysical significance of the Principle was fully developed.`}</P>

        <P>{`Ch'eng Hao is noted for his self-realization of the Heavenly Principle, which naturally operates in the perpetual production and reproduction of myriad things. Lacking this Heavenly Principle in their metaphysics, he contended, "the Buddhists do not understand yin and yang, day and night, life and death, or past and present. How can it be said that their metaphysics is the same as that of the Sage?"(36) But he did not trouble himself to give a thorough ontological explication of the Heavenly Principle, because he was primarily concerned with how to attain to the harmonious unity of Heaven (Nature) and man.`}</P>

        <P>{`The Neo-Confucian metaphysical criticism of Mahaayaana transcendentalism reached its peak in the dualistic rationalism of Ch'eng Yi and Chu Hsi. Both believe that through our exhaustive investigation of myriad things we can discover in them specific real principles or reasons of being, all of which are but the ontological differentiations of the one and the same Heavenly Principle or, in Chu Hsi's case, Supreme Ultimate. In the unceasing process of the production and reproduction of myriad things, we find the interaction of yin and yang and the successive movements of the five elements in due order, all of which are but the cosmological manifestations of the Heavenly Principle. Following the famous statement in the Appended Remarks to the Classic of Changes, "What is above shapes (metaphysical) is called Tao (the Way), and what is within shapes (phenomenal) is called concrete things, "(37) Ch'eng-Chu rationalists regard the Heavenly Principle or Supreme Ultimate as the metaphysical Tao, and yin-yang, five elements, and all concrete things as phenomenal differentiations of ch'i, materializing the Heavenly Principle into innumerable forms of things in the universe.`}</P>

        <P>{`The Principle is all-complete in itself, ontologically prior to ch'i, and eternally subsistent; it is, however, inseparable from ch'i as far as the formation of things is concerned. Applying their metaphysical assumption "Principle is one but its manifestations are many" to human nature, Ch'eng-Chu rationalists maintain that human nature is twofold: moral (heavenly) nature and physical nature. The principles of humanity, righteousness, propriety, and Wisdom--all of which are differentiated principles of the Supreme Ultimate--constitute the moral or heavenly nature in its original state. When this nature`}</P>

        <OL start='35'>
          <li>{`Ibid., 2:2B.`}</li>
          <li>{`Source Book, p. 542.`}</li>
          <li>{`My translation. See also Source Book, p. 267.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.384`}</H3>

        <P>{`is implanted in ch'i, it becomes physical nature differentiated in terms of clear/turbid, pure/impure, etc. Hence, different capacities, talents, feelings, desires, etc., are discernible in different men--the best kind of men being those receiving the Mean (perfect balance) of ch'i. Further, they adapted Chang Tsai's theory of "the mind unifying nature and passions" and regarded the mind as a kind of receptacle in which all moral principles identical with the tranquil heavenly nature are fully "stored" and human desires and feelings activated. When human desires increase, the heavenly principle decreases; when the latter increases, the former decrease. The attainment to sagehood now means the total transformation of physical nature into the original nature of heaven-and-earth.`}</P>

        <P>{`Thus, from the standpoint of their moral metaphysics of li-ch'i(al) duality, (1) the mind is full of moral principles and is not empty, (2) the nature is (real) principle, and (3) there is the ultimate heavenly principle manifested in the production and reproduction of myriad things. Through their reconstruction of the principle of sublime transcendence in this manner, both Ch'eng Yi and Chu Hsi make a clear distinction between Confucianism and Buddhism in terms of real/unreal or right/wrong principles. They often quoted the famous line in the Classic of Odes "The hawk flies up to heaven and the fishes leap in the deep"(38) to illustrate the creative operations of the Heavenly Principle in the entire universe. The Buddhists, they would say, could never understand the deep metaphysical meaning of this line as well as of Confucius' words "Like this stream, everything is flowing on ceaselessly, day and night," because they find no real principle behind the transient stream-of-life (anitya). They could not understand either that human nature is real, for nature is to them unreal or empty (suunya) also. As Chu Hsi said,"We Confucianists regard nature as real, while the Buddhists regard it as empty."(39) He made it clear that the essential difference between Confucianism and Buddhism is not merely moral, but rather metaphysical in a deeper sense. That the principle of sublime transcendence sometimes functions as a more important criterion than does the principle of jen-yi in Chu Hsi's criticism of Buddhism can be easily detected from the following passage:`}</P>

        <Quot>{`Lu Hsiang-shan says that the Buddhists and the Confucianists share the same view and that the only difference lies in the distinction between righteousness and profit. I think this is wrong. If what Lu says were right, we Confucianists and the Buddhists would then maintain the one and same doctrine. If this were the case, can there be any difference at all even in terms of the righteousness /profit distinction? The truth is that the fundamental point is different: We Confucianists say all principles are real while they say all principles are empty.(40)`}</Quot>

        <OL start='38'>
          <li>{`Ibid., p. 100.`}</li>
          <li>{`Chu Tzu yu-lei, vol. 1, p. 102`}</li>
          <li>{`Ibid., vol.7, p. 4766.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.385`}</H3>

        <P>{`While Ch'eng-Chu rationalists hold the view that nature is Principle, the idealists Lu Hsiang-shan and Wang Yang-ming, both faithful followers of Mencius, insist that "the mind is Principle." They flatly reject any principle existing apart from the mind and explore more deeply the metaphysical dimension of Mencius' (moral) mind as originally good to such an extent that the mind of jen-yi is now identified with the mind of heaven-and-earth (universe). Like Mencius, Lu-Wang idealists teach that everyone can become a sage if he constantly and naturally nourishes his moral endowments to the utmost. Wang even asserts that the innate knowledge of the good constitutes the ontological substance of the mind, which transcends both good and evil (in the relative sense). In spite of their tendency to be affiliated with Zen, both Lu and Wang are quite clear about the fundamental difference between them and Zen Buddhists; to them as well as to other orthodox Neo-Confucianists, the sublime transcendence of Confucianism is never divorced from the Mean in everyday moral practice. Lu is therefore able to say that "Moral Principles inherent in the human mind are endowed by Heaven and cannot be wiped out" and that "The affairs within the universe are my own affairs, and my own affairs are the affairs within the universe."(41) From this standpoint of moral idealism, Lu would not accept any Zen doctrine of no-mind (wu-hsin).(am) As he says, "Man is not wood or stone, how can he have no mind?"(42) In the case of Wang Yang-ming, his "Zennist" conception of the substance of the mind as "neither good nor evil" may have caused much misunderstanding, but he never deviated from the Confucian principle of sublime transcendence right in everyday moral practice, as evidenced by the following conversation with his disciples:`}</P>

        <Quot>
          <P>{`Someone said, "The Buddhists also devote themselves to the nourishing of the mind, but fundamentally they are incapable of governing the world. Why?"`}</P>
          <P>{`The teacher said, "In nourishing the mind, we Confucianists have never departed from things and events. By merely following the natural principles of things we accomplish our task. On the other hand, the Buddhists insist on getting away from things and events completely and viewing the mind as an illusion, gradually entering into a life of emptiness and silence, and seeming to have nothing to do with the world at all. This is why they are incapable of governing the world."(43)`}</P>
        </Quot>

        <P>{`Thus, both Lu-Wang idealists and Ch'eng-Chu rationalists use the same Confucian principle of sublime transcendence right in the Mean of everyday moral practice as the principal weapon in their attack against Mahaayaana conception of no-mind and human nature. And their attack here leads them further to the disagreement with Zen Buddhists on the method and practice of`}</P>

        <OL start='41'>
          <li>{`Source Book, p. 580.`}</li>
          <li>{`Lu Hsiang-shan ch'uan-chi(bs) [Complete works of Lu Hsiang-shan] (Taipei: World Book Co., 1959), vol. 1, p. 95.`}</li>
          <li>{`Wang Yang-ming, Instructions, p. 220.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.386`}</H3>

        <P>{`mind-cultivation. First, they criticize the latter that they only engage in quiet sitting-in-meditation (tso-ch'an(an)), without being able to practice ching(ao) (earnest attentive-mindedness or nonattached one-mindedness), or nourish the mind so as to penetrate both activity and tranquility. The Buddhists are sometimes accused of being "never righteous [enough] to square the external, though one-minded [enough] to straighten the internal."(44) From the Neo-Confucian point of view, the real Mean consists in the Way to unite both the internal (complete equilibrium before activity) and the external (perfect harmony in activity). "It is not difficult to sit quietly alone; but it is difficult to stay in the public place and respond to the world affairs."(45) Further, instead of nonabiding samaadhi (concentration) in Zen, the Neo-Confucianists recommend the combined practice of chih(ap) (proper abiding) and ting(aq) (composure) in our handling of daily affairs.(46) Chu Hsi says that the Buddhists know only how to keep the substance of the tranquil mind, which cannot function properly in everyday activities; whereas the Confucianists always find the real substance of the mind right in its everyday moral functioning. In short, substance and function in Buddhist (Zen) doctrine of the mind are divorced from each other, while in the Confucian tradition, both substance and function of the (moral) mind are harmoniously united.`}</P>

        <P>{`The conclusion the orthodox Neo-Confucianists reach after their critical examination of Buddhist Weltanschauung and Lebensanschauung, as well as of Buddhist theory of the mind and method of mind-cultivation, is that there is nothing worthwhile to learn from Buddhism. "It is more rewarding to read just the ken-kua(ar) ("stilling" hexagram) in the Classic of Changes than the whole Avata^msaka Suutra."(47)`}</P>

        <H3 style={{ textAlign: 'center' }}>{`III`}</H3>

        <P>{`One might wonder what is left in Mahaayaana Buddhism to defend against the Neo-Confucian devastating attacks I have just discussed.(48) The truth seems`}</P>

        <OL start='44'>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 1, Yi-shu, 4:4B.`}</li>
          <li>{`Op. cit., 7:2A.`}</li>
          <li>{`Both chih and ting are first mentioned in the Great Learning. See Source Book, p. 86. For the Confucian meaning of ting, see ibid., p. 88.`}</li>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 1, Yi-shu, 6:2A.`}</li>
          <li>{`There are a number of Buddhist apologetic works against Neo-Confucian criticism, such as Li Ch'un-fu's(bt) Ming-tao chi-shuo(bu) , Hsin-t'ai's(bv) Fo-fa chin-t'ang pien(bw), and T'u Lung's(bx) Fo-fa chin-t'ang lu(by). The main purpose of these works, except T'u Lung's, is to attempt a syncretic unity of Buddhism and Confucianism (and Taoism). As Kubota notes, only T'u Lung really engaged himself in the direct confrontation with Neo-Confucianism and defended Buddhist truth to the last minute. See Kubota's Shina judobutsu sankyo shiron(bz) [A historical treatise of the three teachings of Confucianism, Taoism, and Buddhism in China] (Tokyo: Toyo Bunko, 1930), p. 660. Since none of the above Buddhist authors did have, it seems to me, a complete understanding of Maahaayana philosophy, I shall present my own philosophical clarification of Mahaayaana Buddhism.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.387`}</H3>

        <P>{`to me, however, that Neo-Confucian criticism of (Mahaayaana) Buddhism is based on a very superficial understanding, or, in some cases, a total distortion of the original meanings of Buddhist doctrines, especially Mahaayaana doctrines. While the Neo-Confucianists overexaggerate the escapist tendency in Buddhism, they completely ignore, intentionally or not, almost all essential ideas of Mahaayaana Buddhism, such as the doctrine of twofold truth, the bodhisattva ideal, the notion of the universal Buddha-nature, and above all the central principle of (Mahaayaana) Buddhism, namely, the Middle Way (madhyamaa pratipad) .(49) Chu Hsi's statement, "The very best of Buddhist doctrines is actually a plagarization of the Taoist teachings of Chuang Tzu and Lieh Tzu....and the words of Zen Buddhists originally came from the leftovers of the pure conversations (ch'ing-t'an(as) ) of the Neo-Taoists, " is just one typical example of Neo-Confucian prejudice against Buddhism in general.(50)`}</P>

        <P>{`First, the Neo-Confucian accusation of Buddhism that it invents the myth of sa.msaaric world-systems, karmic retribution, the Pure Land (sukhaavatii) and numerous hells, etc., to scare people or make a selfish escape from this world is pointless. Buddhism is never a system of pure objective truth about the reality of the world and man. It does not even have any fixed "absolute truth" (paramaarthasatya) of its own. In Buddhism, particularly Mahaayaana, truth is no more than upaayakau'salya (skillful, pedagogical device) for the sake of enlightenment (nirvaa.na).(51) From the Mahaayaana point of view, truth makes sense only if one remains ignorant (avidyaa); as soon as one is awakened to one's "original face" so to speak, the so-called truth will silently slip away. Only in this light can we appreciate well the nature of the Four Noble Truths announced by the historical Buddha. Whether Theravaada Buddhists agree, all Mahaayaana philosophers since Naagaarjuna are firmly convinced that the Four Noble Truths are at best conventional truth (sa^mv.rtisatya) and should not be taken for granted. The essential point here is that, in Mahaayaana philosophy at least, there is always an inseparable relation between (1) states of mind (perspectives or standpoints), (2) levels of truths (judgments or statements), and (3) degrees of reality (ontological nature of things), the`}</P>

        <OL>
          <li>{`I have done my best to check all primary sources of Neo-Confucianism, but find, to my great surprise, none of the orthodox Neo-Confucianists who ever mentioned the term "Middle Way."`}</li>
          <li>{`Chu Tzu ta-ch'uan, vol. 12, Shih-shih lun(ca) [On Buddhism], II.`}</li>
          <li>{`Buddhist truth is often likened to a raft (for crossing over to the "other shore"), a fish trap (of no use after all fish needed are caught), or a finger (pointing to the moon). The following expression from the Saddharmapu.n.dariika is perhaps most illustrative of the nature of upaaya: "Although the Tathagata has not entered Nirvana, he makes a show of entering Nirvana, for the sake of those who have to be educated," in Edward Conze, ed., Buddhist Texts through the Ages (Oxford: Bruno Cassirer, 1954), p. 142. For a full discussion of upaaya, see Bhikshu Sangharakshita, A Survey of Buddhism (Bangalore: Indian Institute of World Culture, 1957), pp. 210-220.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.388`}</H3>

        <P>{`states of mind being always the Archimedean point.(52) In other words, all degrees of reality [things --> dharmas (experiential factors of existence) --> sarvadharma'suunyataa (emptiness of all dharmas) --> bhuutatathataa (suchness or as-it- is-ness) ] described by Mahaayaana Buddhists presuppose the respective levels of truth, which again presuppose the respective points of view in accordance with the respective higher or lower states of mind. The famous Mahaayaana maxim "The triple world is unreal and is created by the mind only" emphasized by the Avata^msaka Suutra should be understood in this sense.`}</P>

        <P>{`Thus, Buddhist statements such as "Life is du.hkha (suffering or imperfection)," "All events in the wheel-of-life are relationally co-originated (pratiityasamutpaada)," or "There is a way toward the cessation of du.hkha (nirodha) " cannot be naively accepted as eternal truth. For example, the Second Noble Truth about the relational co-origination of all things in terms of the beginningless chain of twelve links (nidaanas) could have at least two hermeneutic versions: if we take what I would call the "vertical" (literal) version accepted by popular Buddhists, then karmic retribution or rebirth would have to be factually true; if we take the "horizontal" (experiential) version in terms of the process of existential Erleben (lived-experience), then the problem of karmic retribution in three successive lives or rebirth would turn out to be very unessential or insignificant. As Edward Conze notes, the "horizontal" version could be more archaic than the "vertical" one.(53) As far as the ultimate goal of Buddhism--the creation of a perfectly enlightened mind--is concerned, whether or not there is rebirth is therefore beside the issue. Without understanding the "pragmatic" nature of (Mahaayaana) Buddhist truth about rebirth, hells, and all other supranatural elements, the Neo-Confucian first attack upon (Mahaayaana) Buddhism completely misses the real target.`}</P>

        <P>{`Another important attack the Neo-Confucianists launch is that Mahaayaana Buddhism regards the world and man as ontologically unreal and that it sets up a vacuous metaphysical principle to support its negativistic Weltan-`}</P>

        <OL>
          <li>{`It should be stressed in this connection that there is always an inseparable relation between theory and practice, objective truth and subjective realization, philosophy and religion, in Buddhism.`}</li>
          <li>{`Buddhist Thought in India (Ann Arbor, Michigan: University of Michigan Press, 1967), p. 157. Cf. also Kenneth K. Inada, "Buddhist Naturalism and the Myth of Rebirth," International Journal for Philosophy of Religion 1, no. 1 (1970). Inada makes a very strong claim here that "the concept of rebirth is naturalistic and ontologically oriented. Its use is strictly limited to the momentary becoming process in man in this life. The myth of rebirth is applicable to the microscopic life-process, the infinite-small moment to moment existence. Any reference to an after-death process would simply be absurd and result in a contradiction of terms," p. 52.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.389`}</H3>

        <P>{`schauung and Lebensanschauung. This criticism again only exposes the Neo-Confucianists' own ignorance of Mahaayaana metaphysics grounded in the Middle Way. The greatest contribution of Mahaayaana philosophers is that they present the ultimate question about the Absolute in terms of things-as-they-really -are (yathaabhuutam) seen (personally realized) by the historical Buddha and try to solve this question by applying the principle of the Middle Way from beginning to end. They ask: Suppose, hypothetically, we are all enlightened as the Buddha himself sub specie aeternitatis, then what sort of transcendental wisdom (praj~naa) can we share with him? And what is the Absolute or Ultimate Reality "intuited" by a man of perfect wisdom? It is in order to answer this ultimate question that all Mahaayaana philosophers since Naagaarjuna have tried to speculate by exploring all possible points of view, such as Maadhyamika, Yogaacaara, the Tathaagatagarbha thought, T'ien-t'ai(at) (the Lotus school) , Hua-yen, or Zen. They are different Mahaayaana schools to be sure, but all of them subscribe to the same fundamental principle, the Middle Way. They all agree on the real nature of the Absolute, if it is, that it is ontologically nondifferentiatable (nondualistic) though epistemologically differentiated (through the mental fabrication of the nonenlightened) . Epistemologically we dichotomize reality-as-it-is (tathataa) into the Absolute and the phenomenal, and this dichotomy presupposes the duality of our (ignorant) mind. Our dual mind establishes two kinds of truth in order to describe the Absolute and the phenomenal respectively; and what is asserted as real from the mundane point of view is to be denied of its reality from the transcendental point of view. If the phenomenal world, sa.msaara, the realm of events (shih), form, etc., are taken as real from the standpoint of worldly truth, they are denied of their own-being (svabhaava) from that of transcendental truth, which instead establishes suchness, nirvaa.na, the realm of Principle (li), dharmakaaya (the Law-body), etc., as real. In short, the phenomenal mind takes the worldly point of view to establish a conventional truth about the reality of the world of appearance; and the transcendental mind takes the higher point of view to establish a higher truth about the unreality of the phenomenal world and the reality of the noumenal.`}</P>

        <P>{`But the Mahaayaana analysis of this epistemological duality of the mind, the truth, and the reality is at best the final pedagogical device to lead the Buddhists to the stage of perfect enlightenment, if they are still one removed from it. Once the last maayaa (illusion) or avidyaa (ignorance) is removed, the transcendental wisdom of the ontologically nondifferentiatable would naturally emerge in the nondualistic mind. The Middle Way now steers between all pairs of "perverted views" (viparyaasa) : Paradoxically, nirvaa.na is now sa^msaara and vice versa, emptiness is now form and vice versa, the realm of Principle is now the realm of Events and vice versa, the absolute`}</P>

        <H3 style={{ textAlign: 'center' }}>{`P.390`}</H3>

        <P>{`mind is now the phenomenal mind and vice versa, transcendental truth is now mundane truth and vice versa, etc.(54) The absolute mind, the transcendental truth, emptiness, or nirvaa.na are all provisional names (praj~naapti) based on our thought-constructions; their existence is, so to speak, "parasitic" upon the existence of the phenomenal mind, the mundane truth, form, or sa^msaara. In other words, if no mundane truth is constructed, there is no necessity to create an absolute truth to refute it. To say that the world is real is a one-sided view (mundane truth), but to say that the world is unreal is again another one-sided view on a higher level (transcendental truth). If the former view is discarded, the latter view will disappear altogether: herein lies the real Middle Way.(55) If the principle of the Middle Way in Mahaayaana Buddhism is understood this way, it is senseless to speak of its metaphysical principle as real or "vacuous." Failing to comprehend Mahaayaana metaphysics in terms of the Middle Way through and through, the Neo-Confucianists mistakenly treat, as did many European Buddhist scholars generations ago, Mahaayaana Buddhism as sheer negativism.`}</P>

        <P>{`Conze once gave us a misleading interpretation of the word "'suunyataa" as follows:`}</P>

        <Quot>{`Roughly speaking we may say that the word as an adjective ('suunya) means 'found wanting' and refers to worldly things, and as a noun ('suunyataa) means inward 'freedom' and refers to the negation of this world....When in China Buddhism fused with Neo-Taoism, 'emptiness' became the latent potentiality from which all things come forth, and it became usual to say, in a cosmological sense, that all things go out of emptiness and return to it. None of all this is intended here....As a practical term 'emptiness' means the complete denial or negation of this world by the exercise of wisdom, leading to complete emancipation from it.(56)`}</Quot>

        <P>{`It is doubtful that early Indian Buddhists thought of emptiness and nirvaa.na in terms of "the complete denial or negation of this world" as Conze interprets here. But even if this were the case, their escapist tendency was corrected first by Naagaarjuna and his Maadhyamika followers, then by the life-affirming Chinese Mahaayaanists. And it is important to point out that Naagaarjuna's "negativistic" logico-ontological analysis of the epistemological duality of the mind, the truth, and the reality constructed by men as well as of the onto-logical nondifferentiatability of nirvaa.na / sa^msaara, absolute/relative, etc., is finally transformed into a direct, positive, and dynamic affirmation of the reality of the phenomenal world and everyday life--an interesting example of`}</P>

        <OL start='54'>
          <li>{`Naagaarjuna says it well: "Sa^msaara is nothing essentially different from nirvaa.na. Nirvaa.na is nothing essentially different from sa^msaara," in Kenneth K. Inada, trans., Naagaarjuna (Tokyo: Hokuseido, 1970), p. 158.`}</li>
          <li>{`Op. cit., p. 148. Here Naagaarjuna declares that "whatever is relational origination is 'suunyataa. It is a provisional name... for the mutuality (of being) and, indeed,it is the middle path."`}</li>
          <li>{`Conze, Buddhist Thought in India, pp. 60-61.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.391`}</H3>

        <P>{`Chinese emphasis on transcendence-in-immanence. The T'ien-t'ai philosophers are able to say, on the basis of the principle of perfectly harmonious three-fold truth, that "Everything, a color or a fragrance, is none other than the Middle Way," which manifestly displays the affirmative restoration of the entire phenomenal world. But it is in the totalistic philosophy of the Hua-yen school and Zen Buddhism that a dynamic and naturalistic reemphasis on the reality of the phenomenal world and everyday life is explicitly placed. This is probably the best example of the Sinicization of Indian Buddhism. In the case of the Hua-yen "round" doctrine of realms embracing realms non-obstructively, only the final realm of (the totality of) Events-and-Events harmoniously merging into one another is regarded as "the ultimate and the only Dharmadhaatu that truly exists. The other three Dharmadhaatus...are merely explanatory expedients to approach the fourth Dharmadhaatu of shih-shih wu-ai(au) [nonobstructive interpenetration of Events-and-Events]."(57) One more step from here and we reach the stage where Zen Buddhists say "Every day is a good day" or "Everyday-mindedness is Tao." In Zen, all Mahaayaana doctrines are simply "put behind one's brain" (p'ao-chu nao-hou(av)), if not denied of their truth. In Zen, one must certainly give up the Buddhist quest for the absolute reality/truth and forget spontaneously that one is giving up the quest. Only then one is said really to "see into one's nature and attain Buddhahood." It is in this sense that we can say, to use my own jargon, "Emptiness works wonders in everyday life." Zen is indeed a happy combination of Buddhist transcendentalism and Taoist naturalism.(58) Thus, the greatest mistake in the Neo-Confucianists' attack against Mahaayaana metaphysics is that they read too much of the Conzean "emptiness" into the context of Mahaayaana Buddhism in China. Hence their baseless criticism.`}</P>

        <P>{`A further Neo-Confucian attack upon Buddhism, Zen in particular, is that its quietist cultivation of the mind lacks dynamic functioning in daily activities, and that the no-mind of Zen is as dead as a withered tree and is therefore useless in everyday moral practice. All great Zen masters since Hui-neng would retort that this criticism is utterly erroneous, for, they would say, in the Zen teaching of mind-cultivation, there is always a strong emphasis on what is called "the great functioning of the great potentiality" (ta-chi ta-yung(aw)).(59) If Sitting or resting is Zen, walking or acting is equally Zen. Even in the flowering age of Neo-Confucian thought in the Southern Sung dynasty, Ta-hui Tsung-kao(ax) was drastically opposed to the quietist approach`}</P>

        <OL start="57">
          <li>{`Garma Chang, The Buddhist Teaching of Totality (University Park: Pennsylvania State University Press, 1971), p. 153.`}</li>
          <li>{`The Taoist tone of the Zen way of life can be found in the poem about everyday-mindedness: "Drinking tea, eating rice, I pass my time as it comes;... How serene and relaxed I feel indeed," in Chang Chung-yuan(cb) , trans., Original Teachings of Ch'an Buddhism (New York: Pantheon Books, 1969), p. 141.`}</li>
          <li>{`Op. cit., p. 186.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.392`}</H3>

        <P>{`of "silent illumination" and took a dynamic approach to Zen for the purpose of perfect functioning in everyday affairs.(60) Small wonder that a great number of troubled Confucian scholars and officials begged for his help.`}</P>

        <P>{`Regarding the nature of Zen no-mind or mind-of-nonabiding, Zen Buddhists would reply that the words like "no-mind," "no-thought," "no-form," or "nonabiding" should not create a linguistic barrier to such an extent that the Zen mind is identified with a dead thing. In reality, all these terms are used to point to the nonduality of the Buddha-nature or One-mind (ekacitta) , which is totally free from the duality of right/wrong, good/evil, etc., in the mundane (relative) sense. It does not follow from this that the authentic Zen Buddhists would not engage themselves in everyday moral practice. On the contrary, they would rather think that only by means of breaking off the dualistic shackles constructed by the ignorant mind is one able to work real wonders in handling human affairs. They could even say that the real Zen mind of nonabiding is no more than the Mencian moral mind transcended, not denied! Interestingly, it was mainly due to the influence of this Zen rediscovery of the transcendental or nondualistic dimension of the mind that Wang Yang-ming could not help introducing the "Zennist" notion of the mind into his moral idealism. Hence his instruction about the substance and function of the mind as follows: "In the original substance of the mind there is no distinction between good and evil. When the will becomes active, however, such distinction exists."(61) Since Zen Buddhists do not deny human morality, they of course would not register any objection to such an idea. And it is actually not difficult to find some evidence to support my interpretation of Zen here. Wing-tsit Chan(ay), for instance, acutely observes, "According to him [Zen Master Lin-yu(az)] on the level of absolute truth there is only one nature, which is free of any contamination such as the distinction between right and wrong or subject and object, but on the level of worldly truth, Buddhism does not discard any element of existence and therefore exhorts the minister to be loyal and the son to be filial."(62)`}</P>

        <H3 style={{ textAlign: 'center' }}>{`IV`}</H3>

        <P>{`From the above philosophical clarification of Mahaayaana thought, it would not be unfair to say that most of Neo-Confucian attacks against (Mahaayaana) Buddhism are based on either misunderstanding or distortion. It seems to me, however, the Neo-Confucian ethico-social criticism of Buddhism, in general,`}</P>

        <OL start='60'>
          <li>{`See Kengo Araki(cc) , Bukkyo to jukyo(cd) [Buddhism and Confucianism] (Kyoto: Heirakuji Shoten, 1963), pp. 196-228. Also his Daie sho(ce) [Zen Letters of Ta-hui], vol. 17 of Zen no goroku(cf) [Conversational Records of Zen] (Tokyo: Chikuma Shobo, 1969), pp. 64-65.`}</li>
          <li>{`Wang Yang-ming, op. cit., p. 243. Set also Source Book, p. 686.`}</li>
          <li>{`Ibid., pp. 647-648.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.393`}</H3>

        <P>{`requires our serious attention and should not be brushed off as senseless or pointless. The orthodox Neo-Confucianists believe that "the Buddhist harm is far greater than Yang Chu and Mo Tzu,"(63) for it is completely against the Confucian principle of gradational love beginning with filial piety and brotherly love.(64) Even the Chinese Buddhists themselves have been very sensitive to the problem of filial piety, which they must tackle in order to resolve the ideological confrontation between their imported religion and the Confucian tradition. As Ryoshu Michihata(ba) points out, traditionally China has been the country that unconditionally accepted the Confucian culture of filial piety, and anybody who did not practice this cardinal virtue was always treated like a man who committed the gravest sin of lese-majeste. The most difficult task of the Chinese Buddhists is not to make a direct, face-to-face confrontation with Confucianism, but rather to effect a necessary compromise by means of a partial Confucianization of their doctrines. One striking example is that, to meet the criticism of the Confucianists, they sometimes reply that their "leaving home" (ch'u-chia(bb))(65) is actually the greatest filial piety, for they can help their parents (as well as others) attain to the Buddhahood of supreme happiness. But the halfway compromise of Chinese Buddhism with the Confucian tradition would not satisfy the hard demand of the orthodox Confucian philosophers, to all of whom the principle of gradational love is the alpha and omega of human morality. That the principle of gradational love is used by the Neo-Confucianists as the ultimate criterion for their refutation of Buddhist heterodoxy is clearly evidenced by Chu Hsi in the following statement:`}</P>

        <Quot>{`Yang Chu originally had no intention at all of plucking out a single hair to benefit the entire world, and yet he said the world could not be benefited by just plucking his single hair; Yi Tzu originally advocated love without distinctions or gradation, and yet he said its practice should start with love of parents; the Buddha [and the Buddhists] need no parents of their own, and yet chat about filial piety. All of these are but quibbles!(66)`}</Quot>


        <P>{`Even if the orthodox Neo-Confucianists accepted all the points I have clarified for Mahaayaana Buddhism, they would not give up their charge against the Buddhist lack of gradational love, which is to them the only way to practice jen.`}</P>

        <OL start='63'>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 3, Ts'ui-yen(cg) [Pure Words], 1:7B.`}</li>
          <li>{`"Filial piety and brotherly love are the starting point for the practice of jen," in the Analects, 1:2. My translation here is based on Ch'eng Yi's unique way of reading the original sentence in the Analects.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.394`}</H3>

        <P>{`When someone asked Ch'eng Hao "How is the Way," his reply was: "It should be found in [the concrete human relations between] sovereign and minister, parent and child, elder brother and young brother, friend and friend, husband and wife."(67) To the Confucian moralist, the Buddhist is just like a person who cannot love his relatives and neighbors in the concrete sense, though he may be able to love humanity at a distance; they are, in making such a transmoral leap, violating the fundamental moral principle of jen-yi. The Neo-Confucian accusation against Buddhism on this point is at least applicable to quite a great number of Buddhists in China whose only interest in this life is simply to escape into a Buddhist monastery at the expense of leaving their parents, wives, children, or brethren at home. In the Record of the Transmission of the Lamp, for instance, we may find a number of cases in which Zen masters, when they were still children, begged their parents to let them withdraw from the world (ch'u-chia) for the sake of enlightenment. As Zenryu Tsukamoto(bc) observes, Mahaayaana Buddhism in China did transform self-concerned Hiinayaanism into a religion of universal salvation; in practice, however, the traditional Mahaayaanists in China still have a strong tendency to escape from what they call "the dusty world" (ch'en-shih(bd)) into loftier and quieter places like mountains and forests. And despite their strenuous efforts to break off the otherworldly shackles of Buddhism, both Zen and Pure Land Buddhists have never successfully overcome the practical weakness of Mahaayaana Buddhism in China.(68) One typical case is that of Hui-neng, the Sixth Patriarch of Zen, who when young happened to be awakened to the Way upon hearing the Diamond Suutra, then decided to leave his poor, widowed mother and went to Mount Feng-mu to make obeisance to the Fifth Patriarch, Hung-jen. In practice he himself withdrew from the world, though in theory he instructed his disciples as follows:`}</P>

        <P>{`Learned Audience, those who wish to train themselves (spiritually) may do so at home. It is quite unnecessary for them to stay in monasteries....`}</P>

        <P>{`On the principle of gratefulness, we support our parents and serve them filially.`}</P>

        <P>{`On the principle of righteousness, the superior and the inferior stand for each other (in time of need).(69)`}</P>

        <P>{`The traditional Zen Buddhists in China seem to have been very much satisfied with the spontaneous, enlightened life described by P'ang Yun's(be)`}</P>

        <OL start='67'>
          <li>{`Erh-ch'eng ch'uan-shu, vol. 2, Wai-shu, 12:10A.`}</li>
          <li>{`See Zenryu Tsukamoto, Chugoku bukkyo shi(ch) [A history of Chinese Buddhism], reprinted in Chugoku no bukkyo(ci) [Buddhism in China], vol. 5 of Gendai bukkyo meicho zenshu(cj) (Tokyo: Ryuubunkan, 1965), p. 336.`}</li>
          <li>{`Wong Mou-lam, trans., The Sutra of Wei Lang, reprinted as Sutra Spoken by the Sixth Patriarch on the High Seat of "The Treasure of the Law" (Hong Kong: Buddhist Book Distributor Press), p.44.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.395`}</H3>

        <P>{`gaathaa on "carrying water and chopping wood."(70) But, in his critical examination of Zen, Fung Yu-lan(bf) makes a very thoughtful remark:`}</P>

        <Quot>{`However, if carrying water and chopping wood are all manifestations of the wondrous Way, why do those [Zen Buddhists] who cultivate the Way have to leave the world? Why isn't "one's service to parents and sovereign" taken to be the wondrous Way? The mission of Neo-Confucianism in the Sung and Ming dynasties is exactly to create such a turning point.(71)`}</Quot>

        <P>
          {`The Neo-Confucian mission is, as I understand it, to carry out to the utmost the Confucian ideal of sublime transcendence right in everyday moral practice through gradational love, wherein is found the essence of the Confucian Mean. That is why the Neo-Confucianists often lament that although Buddhism is loftier and more transcendental than the teaching of Chuang Tzu, it is still weak in not following the path of the everyday Mean.(72)`}
        </P>

        <P>
          {`In their teaching of enlightenment, Zen masters often use the expression "To make a further leap after climbing up onto the top of the pole 100-feet high." But Neo-Confucian philosophers would ask: In order to make such a final leap toward enlightenment, why do you have to escape into a Buddhist monastery? And why shouldn't the enlightenment-taste of "Every day is a good day" be realized right in what you Buddhists (as well as Taoists) call the dusty world? Although to be or not to be a Buddhist monk ("one who leaves home") is in some cases a matter of existential self-commitment, the above hard-hitting point made by the Neo-Confucianists in their ethicosocial criticism of Mahaayaana Buddhism in China seems to require at least a mature philosophical reflection on the part of Mahaayaana Buddhists themselves.(73)`}
        </P>

        <OL start='70'>
          <li>{`Chang Chung-yuan, op. cit., p. 175.`}</li>
          <li>{`Fung Yu-lan, Hsin yuan-tao(ck) [The new treatise on Tao], p. 163. See also the translation of this book by E. R. Hughes, The Spirit of Chinese Philosophy (London: Kegan Paul, 1947), p. 174.`}</li>
          <li>{`Erh-Ch'eng ch'uan-shu, vol. 1, Yi-shu, 18:11A; vol. 3, Ts'ui-yen, 1:9A. See also Chu Tzu yu-lei, vol. 4, p. 2519.`}</li>
          <li>{`Although I am not concerned in this paper with the problem of the modern reconstruction of Mahaayaana Buddhist thought, I will add a final word here. It seems to me that Mahayana Buddhists should learn a good lesson from the challenge of Neo-Confucianism and engage in a necessary and urgent inquiry into the moral dimension of their own tradition, by shifting their traditional emphasis on transcendental truth to a new emphasis on worldly truth in terms of everyday ethicosocial practice. This shift of emphasis is not an impossible task, if Mahaayaana Buddhists have a perfect understanding of the principle of the Middle Way as well as of the real meaning of the twofold truth in their tradition. In the past, they tended to regard morality ('siila) as primarily a means, discipline, or prerequisite toward the ultimate goal. It is now time for them to develop a new and modern philosophy of the Middle Way by placing equal emphasis on morality as well as on wisdom (praj~naa) and meditation (samaadhi). Further, a new moral wine should be put into the ancient bottle full of karu.naa (universal compassion). But it remains to be seen whether Mahaayaana Buddhists can work out in this modern age an ethical system to tackle most if not all, human and secular problems they encounter in everyday life.`}</li>
        </OL>
        <H3 style={{ textAlign: 'center' }}>{`P.396`}</H3>
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <img src={p396image} style={{ objectFit: 'cover', width: '100%', maxWidth: '600px' }} />
        </div>
      </div>
    </Box>
  );
};

export default Morality;